### ISSUE TITLE
User Guide for Pybpod

### ISSUE THREAD

**Issue by HenryJFlynn** [HenryJFlynn/mouse2afc#25]
I would like to create instructions on how to use pybpod which I can provide to the experiments of the lab and anyone out there that would like to use it. The instructions should include:
1. How to Install
     - Where do you find the files?
     - Where do you install it?
     - set up virtual env
2. How to start
3.  How to use
     - how to set up projects
     - links to help resources
     - which buttons to press and in what order
     - which buttons do what?
     - how to access data after trials

**Comment by HenryJFlynn** [comment]
Initial complete user instructions has been created

**Comment by HenryJFlynn** [comment]
Next steps
1. Try to run through the steps myself to double check it is correct
2. Fix anything that is wrong (missed steps, incorrect steps, typos, etc.)
3. Hand it over to chris
4. Make his suggested changes, if any
5. hand it off to the experimentors

**Comment by HenryJFlynn** [comment]
Should I provide details on the installation of the prerequisites?

**Comment by HenryJFlynn** [comment]
Where should these instructions be? currently in my mouse2afc repo.

**Comment by HenryJFlynn** [comment]
I need to choose a uniform way of saying "excute in termnal" or "in terminal type...". I switch back and fourth. I do not know which is the best way to state it, meaning the most precise and too the point

**Comment by HenryJFlynn** [comment]
Labeling of headings and subheads with numbers is weird, maybe letters instead

**Comment by HenryJFlynn** [comment]
`sudo usermod -a -G dialout [your username]`
![image](https://github.com/HenryJFlynn/mouse2afc/assets/130571023/84980782-0245-4524-8754-fff92307391f)

**Comment by HenryJFlynn** [comment]
There is a bug with the gui which causes the details tab not to load. It stays blank no matter if you select board or setup. When this happens you are unable to rename anything or select a protocol.

**Comment by HenryJFlynn** [comment]
Default user settings
```python
SETTINGS_PRIORITY = 0

GENERIC_EDITOR_PLUGINS_LIST = ['pybpodgui_plugin', 'pybpodgui_plugin_timeline', 'pybpodgui_plugin_session_history']
```

**Comment by HenryJFlynn** [comment]
> There is a bug with the gui which causes the details tab not to load. It stays blank no matter if you select board or setup. When this happens you are unable to rename anything or select a protocol.

I created a new project. Details tab didn't load. Saved the project. closed the project. Reopened. Details tab is working fine

**Comment by HenryJFlynn** [comment]
Following my instructions, I am getting the wire1 not being a valid output error which I encountered when I first tried to get the protocol to work

**Comment by HenryJFlynn** [comment]
When I tried to follow the instructions from scratch, from file explorer, I renamed my environment `pybpod-environment` to `pybpod-environment-main`. I did this to avoid it being over written. The `.yml` file used to create the environment automatically names the environment ` pybpod-environment`. When I go to the `pybpod-environment-main` to run pybpod, i get the same error. So now my original environment has a problem as well as the new one

**Comment by HenryJFlynn** [comment]
I tried to change the names back but that didn't work. Things got worse.
```python
henry@henry-Vostro-270:~/Documents/chris-pybpod$ conda activate pybpod-environment-main
(pybpod-environment-main) henry@henry-Vostro-270:~/Documents/chris-pybpod$ start-pybpod
bash: /home/henry/anaconda3/envs/pybpod-environment-main/bin/start-pybpod: /home/henry/anaconda3/envs/pybpod-environment/bin/python: bad interpreter: No such file or directory
(pybpod-environment-main) henry@henry-Vostro-270:~/Documents/chris-pybpod$ conda activate pybpod-environment
(pybpod-environment) henry@henry-Vostro-270:~/Documents/chris-pybpod$ start-pybpod
bash: /home/henry/anaconda3/envs/pybpod-environment/bin/start-pybpod: /home/henry/anaconda3/envs/pybpod-environment/bin/python: bad interpreter: No such file or directory
```

**Comment by HenryJFlynn** [comment]
still messing around
```
henry@henry-Vostro-270:~/Documents/chris-pybpod$ conda rename -n pybpod-environment-main pybpod-environment

CondaEnvException: The environment 'pybpod-environment' already exists. Override with --force.
``` 
so then i did
```
henry@henry-Vostro-270:~/Documents/chris-pybpod$ conda rename -n pybpod-environment-main pybpod-environment --force
```
and now it is frozen

**Comment by HenryJFlynn** [comment]
I am gonna delete all the environments and start over.

**Comment by HenryJFlynn** [comment]
So i tried to setup a new environment from scratch. Used the `.yml` file to create the environment, then did `python utils/install.py`. There started to be errors:
```
(pybpod-environment) henry@henry-Vostro-270:~/Documents/chris-pybpod$ python utils/install.py
Obtaining file:///home/henry/Documents/chris-pybpod/libraries/logging-bootstrap
Installing collected packages: logging-bootstrap
  Found existing installation: logging-bootstrap 1.0.0
Cannot remove entries from nonexistent file /home/henry/anaconda3/envs/pybpod-environment/lib/python3.6/site-packages/easy-install.pth
You are using pip version 21.3.1, however version 23.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

so i tried to update my pip, but it didn't work

```
(pybpod-environment) henry@henry-Vostro-270:~/Documents/chris-pybpod$ pip install --upgrade pip
Requirement already up-to-date: pip in /home/henry/anaconda3/envs/pybpod-environment/lib/python3.6/site-packages
You are using pip version 21.3.1, however version 23.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
I am lost

**Comment by HenryJFlynn** [comment]
I restarted again. Tracking everything:
```
henry@henry-Vostro-270:~$ conda env create -f Downloads/environment-ubuntu-17.10.yml
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 23.3.1
  latest version: 23.5.0

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.5.0



Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: - Ran pip subprocess with arguments:
['/home/henry/anaconda3/envs/pybpod-environment/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/henry/Downloads/condaenv.lq84u3ys.requirements.txt', '--exists-action=b']
Pip subprocess output:
Collecting anyqt==0.0.8 (from -r /home/henry/Downloads/condaenv.lq84u3ys.requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/7c/32/f6ae3ad3be05722d344ff8d202d4f0382f7fc75e1ad2fd49cc36ccd2e8a7/AnyQt-0.0.8-py2.py3-none-any.whl
Collecting send2trash==1.4.2 (from -r /home/henry/Downloads/condaenv.lq84u3ys.requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/6c/de/17f0fd21a9d6565b7bf32e4747486bf13603252451887b93b4346c2d2690/Send2Trash-1.4.2-py3-none-any.whl
Collecting pandas==0.22.0 (from -r /home/henry/Downloads/condaenv.lq84u3ys.requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/da/c6/0936bc5814b429fddb5d6252566fe73a3e40372e6ceaf87de3dec1326f28/pandas-0.22.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting scipy (from -r /home/henry/Downloads/condaenv.lq84u3ys.requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/c8/89/63171228d5ced148f5ced50305c89e8576ffc695a90b58fe5bb602b910c2/scipy-1.5.4-cp36-cp36m-manylinux1_x86_64.whl
Collecting confapp==1.0.0 (from -r /home/henry/Downloads/condaenv.lq84u3ys.requirements.txt (line 5))
Collecting pytz>=2011k (from pandas==0.22.0->-r /home/henry/Downloads/condaenv.lq84u3ys.requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/7f/99/ad6bd37e748257dd70d6f85d916cafe79c0b0f5e2e95b11f7fbc82bf3110/pytz-2023.3-py2.py3-none-any.whl
Collecting python-dateutil>=2 (from pandas==0.22.0->-r /home/henry/Downloads/condaenv.lq84u3ys.requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl
Collecting numpy>=1.9.0 (from pandas==0.22.0->-r /home/henry/Downloads/condaenv.lq84u3ys.requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/45/b2/6c7545bb7a38754d63048c7696804a0d947328125d81bf12beaa692c3ae3/numpy-1.19.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting six>=1.5 (from python-dateutil>=2->pandas==0.22.0->-r /home/henry/Downloads/condaenv.lq84u3ys.requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl
Installing collected packages: anyqt, send2trash, pytz, six, python-dateutil, numpy, pandas, scipy, confapp
  Found existing installation: pytz 2017.3
    Uninstalling pytz-2017.3:
      Successfully uninstalled pytz-2017.3
  Found existing installation: six 1.11.0
    Uninstalling six-1.11.0:
      Successfully uninstalled six-1.11.0
  Found existing installation: python-dateutil 2.6.1
    Uninstalling python-dateutil-2.6.1:
      Successfully uninstalled python-dateutil-2.6.1
  Found existing installation: numpy 1.13.3
    Uninstalling numpy-1.13.3:
      Successfully uninstalled numpy-1.13.3
Successfully installed anyqt-0.0.8 confapp-1.0.0 numpy-1.19.5 pandas-0.22.0 python-dateutil-2.8.2 pytz-2023.3 scipy-1.5.4 send2trash-1.4.2 six-1.16.0

done
#
# To activate this environment, use
#
#     $ conda activate pybpod-environment
#
# To deactivate an active environment, use
#
#     $ conda deactivate

```

**Comment by HenryJFlynn** [comment]
I now have to clone the repo again and make sure it works

**Comment by HenryJFlynn** [comment]
maybe remain the env first and make sure that works then clone the repo

**Comment by HenryJFlynn** [comment]
Some of the steps could be eliminated if changes were made to the pybpod repo, i.e. in the .yml change the pip it installs to the something more recent.

**Comment by HenryJFlynn** [comment]
I recloned the repo and tried to run it on the environment I created yesterday which worked(https://github.com/HenryJFlynn/mouse2afc/issues/25#issuecomment-1593139292) and I got this error

```python
['stderr', '2023-06-16 10:25:13.211441', '', '    ', '', '']
['stderr', '2023-06-16 10:25:13.211478', '', 'bpod = Bpod(emulator_mode=True)', '', '']
['stderr', '2023-06-16 10:25:13.211511', '', '\n', '', '']
['stderr', '2023-06-16 10:25:13.211533', '', '  File "/home/henry/Documents/chris-pybpod/base/pybpod-api/pybpodapi/bpod/bpod_io.py", line 26, in __init__\n', '', '']
['stderr', '2023-06-16 10:25:13.211618', '', '    ', '', '']
['stderr', '2023-06-16 10:25:13.211653', '', 'super(BpodIO, self).__init__(serial_port, sync_channel, sync_mode, emulator_mode)', '', '']
['stderr', '2023-06-16 10:25:13.211686', '', '\n', '', '']
['stderr', '2023-06-16 10:25:13.211717', '', '  File "/home/henry/Documents/chris-pybpod/base/pybpod-api/pybpodapi/bpod/bpod_com_protocol.py", line 34, in __init__\n', '', '']
['stderr', '2023-06-16 10:25:13.211829', '', '    ', '', '']
['stderr', '2023-06-16 10:25:13.211857', '', 'super(BpodCOMProtocol, self).__init__(serial_port, sync_channel, sync_mode, emulator_mode=emulator_mode)', '', '']
['stderr', '2023-06-16 10:25:13.211881', '', '\n', '', '']
['stderr', '2023-06-16 10:25:13.211913', '', '  File "/home/henry/Documents/chris-pybpod/base/pybpod-api/pybpodapi/bpod/bpod_base.py", line 74, in __init__\n', '', '']
['stderr', '2023-06-16 10:25:13.212026', '', '    ', '', '']
['stderr', '2023-06-16 10:25:13.212063', '', 'self._emulator = Emulator(self._hardware)', '', '']
['stderr', '2023-06-16 10:25:13.212086', '', '\n', '', '']
['stderr', '2023-06-16 10:25:13.212108', '', '  File "/home/henry/Documents/chris-pybpod/base/pybpod-api/pybpodapi/bpod/emulator/emulator.py", line 84, in __init__\n', '', '']
['stderr', '2023-06-16 10:25:13.212193', '', '    ', '', '']
['stderr', '2023-06-16 10:25:13.212219', '', 'self._init_hardware(hardware)', '', '']
['stderr', '2023-06-16 10:25:13.212241', '', '\n', '', '']
['stderr', '2023-06-16 10:25:13.212263', '', '  File "/home/henry/Documents/chris-pybpod/base/pybpod-api/pybpodapi/bpod/emulator/emulator.py", line 117, in _init_hardware\n', '', '']
['stderr', '2023-06-16 10:25:13.212348', '', '    ', '', '']
['stderr', '2023-06-16 10:25:13.212373', '', 'self._hardware.configure_inputs()', '', '']
['stderr', '2023-06-16 10:25:13.212394', '', '\n', '', '']
['stderr', '2023-06-16 10:25:13.212416', '', '  File "/home/henry/Documents/chris-pybpod/base/pybpod-api/pybpodapi/bpod/hardware/hardware.py", line 80, in configure_inputs\n', '', '']
['stderr', '2023-06-16 10:25:13.212499', '', '    ', '', '']
['stderr', '2023-06-16 10:25:13.212524', '', 'self.inputs_enabled[i] = settings.BPOD_BEHAVIOR_PORTS_ENABLED[j]', '', '']
['stderr', '2023-06-16 10:25:13.212546', '', '\n', '', '']
['stderr', '2023-06-16 10:25:13.212573', '', 'IndexError', '', '']
['stderr', '2023-06-16 10:25:13.212595', '', ': ', '', '']
['stderr', '2023-06-16 10:25:13.212616', '', 'list index out of range', '', '']
['stderr', '2023-06-16 10:25:13.212637', '', '\n', '', '']
```

**Comment by HenryJFlynn** [comment]
^^ it is referencing chris-pybpod but we are not in that folder which is strange. I am gonna try to got from scratch again.

**Comment by HenryJFlynn** [comment]
^^ I tried to run pybpod from chris-pybpod and i got the same error

**Comment by HenryJFlynn** [comment]
This fixed the problem. Closed all terminals, reopen a terminal, `conda activate pybpod-environment`,`cd Documents/user-guide-pybpod`,`start-pybpod`, i created a new experiment, and imported a protocol (which was mouse2afc from the project I usually use).

**Comment by HenryJFlynn** [comment]
^^ I created a new project again. This time I added a protocol and pasted mouse2afc into it. It worked

**Comment by HenryJFlynn** [comment]
see https://github.com/ckarageorgkaneen/mouse2afc/pull/6
Going to retry the instructions:
1. Changing the name of my current env isn't straightforward so, i will modify the name of the environment in the .yml file to be pybpod-environment-test
2.

**Comment by HenryJFlynn** [comment]
Restarting again, I still get the wire1 error. I was playing with mismatching the new env and repo with the working env and repo. I got this erroe when using my working repo with the new env
```bash
['stderr', '2023-07-03 15:34:47.717831', '', 'Before StateMatrix()', '', '']
['stderr', '2023-07-03 15:34:47.717976', '', '\n', '', '']
['stderr', '2023-07-03 15:34:47.720716', '', 'Traceback (most recent call last):\n', '', '']
['stderr', '2023-07-03 15:34:47.720824', '', '  File "/home/henry/Documents/pybpod-test2/base/pybpod-api/pybpodapi/state_machine/state_machine_base.py", line 221, in add_state\n', '', '']
['stderr', '2023-07-03 15:34:47.721173', '', '    ', '', '']
['stderr', '2023-07-03 15:34:47.721237', '', 'action_name', '', '']
['stderr', '2023-07-03 15:34:47.721285', '', '\n', '', '']
['stderr', '2023-07-03 15:34:47.721437', '', 'ValueError', '', '']
['stderr', '2023-07-03 15:34:47.721492', '', ': ', '', '']
['stderr', '2023-07-03 15:34:47.721537', '', "'Wire1' is not in list", '', '']
['stderr', '2023-07-03 15:34:47.721581', '', '\n', '', '']
['stderr', '2023-07-03 15:34:47.721626', '', '\nDuring handling of the above exception, another exception occurred:\n\n', '', '']
['stderr', '2023-07-03 15:34:47.721675', '', 'Traceback (most recent call last):\n', '', '']
['stderr', '2023-07-03 15:34:47.721723', '', '  File "/home/henry/Documents/user-guide-project/tasks/mouse2afc-example/mouse2afc-example.py", line 8, in <module>\n', '', '']
['stderr', '2023-07-03 15:34:47.721896', '', '    ', '', '']
['stderr', '2023-07-03 15:34:47.721963', '', 'Mouse2AFC(bpod).run()', '', '']
['stderr', '2023-07-03 15:34:47.722075', '', '\n', '', '']
['stderr', '2023-07-03 15:34:47.722130', '', '  File "/home/henry/Documents/mouse2afc/mouse2afc.py", line 41, in run\n', '', '']
['stderr', '2023-07-03 15:34:47.722297', '', '    ', '', '']
['stderr', '2023-07-03 15:34:47.722415', '', 'self._bpod, self._task_parameters, self._data, i_trial)', '', '']
['stderr', '2023-07-03 15:34:47.722471', '', '\n', '', '']
['stderr', '2023-07-03 15:34:47.722516', '', '  File "/home/henry/Documents/mouse2afc/state_matrix.py", line 539, in __init__\n', '', '']
['stderr', '2023-07-03 15:34:47.722893', '', '    ', '', '']
['stderr', '2023-07-03 15:34:47.722951', '', 'output_actions=(IncorrectChoice_Signal + WaitFeedbackStim))', '', '']
['stderr', '2023-07-03 15:34:47.722997', '', '\n', '', '']
['stderr', '2023-07-03 15:34:47.723044', '', '  File "/home/henry/Documents/pybpod-test2/base/pybpod-api/pybpodapi/state_machine/state_machine_base.py", line 229, in add_state\n', '', '']
['stderr', '2023-07-03 15:34:47.723280', '', '    ', '', '']
['stderr', '2023-07-03 15:34:47.723334', '', '+ " is an invalid output name."', '', '']
['stderr', '2023-07-03 15:34:47.723379', '', '\n', '', '']
['stderr', '2023-07-03 15:34:47.723427', '', 'pybpodapi.state_machine.state_machine_base', '', '']
['stderr', '2023-07-03 15:34:47.723473', '', '.', '', '']
['stderr', '2023-07-03 15:34:47.723517', '', 'SMAError', '', '']
['stderr', '2023-07-03 15:34:47.723560', '', ': ', '', '']
['stderr', '2023-07-03 15:34:47.723603', '', 'Error creating state: Punishment. Wire1 is an invalid output name.', '', '']
['stderr', '2023-07-03 15:34:47.723648', '', '\n', '', '']
```
noticed the fourth stderr 
```
['stderr', '2023-07-03 15:34:47.720824', '', '  File "/home/henry/Documents/pybpod-test2/base/pybpod-api/pybpodapi/state_machine/state_machine_base.py", line 221, in add_state\n', '', '']
```
the repo `pybpod-test2` is being referenced, though I am not in the repo. Are the env and repo linked?

**Comment by HenryJFlynn** [comment]
Retrying. pip error:
```
Cache entry deserialization failed, entry ignored
```
Maybe pip cache, maybe my [network](https://stackoverflow.com/questions/49671215/cache-entry-deserialization-failed-entry-ignored)

**Comment by HenryJFlynn** [comment]
> I made a duplicate of the env, then did `python utils/install.py` again. The compared the env to the duplicate,
> 
> ```shell
> (pybpod-environment-test) henry@henry-Vostro-270:~/Documents/pybpod-test2$ diff -qr /home/henry/Documents/pybpod-environment-test/ /home/henry/anaconda3/envs/pybpod-environment-test/
> Files /home/henry/Documents/pybpod-environment-test/bin/pyfgui and /home/henry/anaconda3/envs/pybpod-environment-test/bin/pyfgui differ
> Files /home/henry/Documents/pybpod-environment-test/lib/python3.6/site-packages/easy-install.pth and /home/henry/anaconda3/envs/pybpod-environment-test/lib/python3.6/site-packages/easy-install.pth differ
> Only in /home/henry/Documents/pybpod-environment-test/lib/python3.6/site-packages: pybpodgui_api
> Only in /home/henry/Documents/pybpod-environment-test/lib/python3.6/site-packages: pybpod_gui_api-1.8.2.dist-info
> Only in /home/henry/anaconda3/envs/pybpod-environment-test/lib/python3.6/site-packages: pybpod-gui-api.egg-link
> ```
> 
> these differences get rid of the wire1 error

Since doing this step again makes the error disappear, there is some change happening to the environment which is causing this. To compare the environment before and after this step, i used the [Meld](https://www.tecmint.com/compare-find-difference-between-two-directories-in-linux/). The two environments are quite different
![image](https://github.com/HenryJFlynn/mouse2afc/assets/130571023/fd25ac8d-000f-491f-8c46-8c3001d7c9a2)
pybpod-env-main is the one which works, -test is one which does not

**Comment by HenryJFlynn** [comment]
![image](https://github.com/HenryJFlynn/mouse2afc/assets/130571023/ad2a94cd-6b88-4375-8ab8-1c95ea5e361e)
vs
![image](https://github.com/HenryJFlynn/mouse2afc/assets/130571023/ee5cdde0-4da8-430d-a49e-b8dc7acdcf42)

The working env has way less files. How?

**Comment by HenryJFlynn** [comment]
When doing `python utils/install.py` again, here is every error:
```bash
Installing collected packages: pybpod-gui-api
  Attempting uninstall: pybpod-gui-api
    Found existing installation: pybpod-gui-api 1.8.2
    Uninstalling pybpod-gui-api-1.8.2:
      Successfully uninstalled pybpod-gui-api-1.8.2
  Running setup.py develop for pybpod-gui-api
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pybpod 1.8.2 requires pybpod-gui-api==1.8.2, but you have pybpod-gui-api 1.8.3b1 which is incompatible.
Successfully installed pybpod-gui-api-1.8.3b1
```
```bash
Installing collected packages: pybpod-gui-plugin
  Attempting uninstall: pybpod-gui-plugin
    Found existing installation: pybpod-gui-plugin 1.8.2
    Uninstalling pybpod-gui-plugin-1.8.2:
      Successfully uninstalled pybpod-gui-plugin-1.8.2
  Running setup.py develop for pybpod-gui-plugin
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pybpod 1.8.2 requires pybpod-gui-api==1.8.2, but you have pybpod-gui-api 1.8.3b1 which is incompatible.
Successfully installed pybpod-gui-plugin-1.8.2
Obtaining file:///home/henry/Documents/pybpod-test/plugins/pge-plugin-terminal
  Preparing metadata (setup.py) ... done
Installing collected packages: pge-plugin-terminal
  Attempting uninstall: pge-plugin-terminal
    Found existing installation: pge-plugin-terminal 0.1
    Uninstalling pge-plugin-terminal-0.1:
      Successfully uninstalled pge-plugin-terminal-0.1
  Running setup.py develop for pge-plugin-terminal
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pybpod 1.8.2 requires pybpod-gui-api==1.8.2, but you have pybpod-gui-api 1.8.3b1 which is incompatible.
Successfully installed pge-plugin-terminal-0.1
```
```bash
Installing collected packages: pybpod-gui-plugin-emulator
  Attempting uninstall: pybpod-gui-plugin-emulator
    Found existing installation: pybpod-gui-plugin-emulator 0.1.5
    Uninstalling pybpod-gui-plugin-emulator-0.1.5:
      Successfully uninstalled pybpod-gui-plugin-emulator-0.1.5
  Running setup.py develop for pybpod-gui-plugin-emulator
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pybpod 1.8.2 requires pybpod-gui-api==1.8.2, but you have pybpod-gui-api 1.8.3b1 which is incompatible.
Successfully installed pybpod-gui-plugin-emulator-0.1.5
Obtaining file:///home/henry/Documents/pybpod-test/plugins/pybpod-gui-plugin-session-history
  Preparing metadata (setup.py) ... done
Installing collected packages: pybpod-gui-plugin-session-history
  Attempting uninstall: pybpod-gui-plugin-session-history
    Found existing installation: pybpod-gui-plugin-session-history 1.4.2
    Uninstalling pybpod-gui-plugin-session-history-1.4.2:
      Successfully uninstalled pybpod-gui-plugin-session-history-1.4.2
  Running setup.py develop for pybpod-gui-plugin-session-history
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pybpod 1.8.2 requires pybpod-gui-api==1.8.2, but you have pybpod-gui-api 1.8.3b1 which is incompatible.
Successfully installed pybpod-gui-plugin-session-history-1.4.2
Obtaining file:///home/henry/Documents/pybpod-test/plugins/pybpod-gui-plugin-stmdiagram
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pydot in /home/henry/anaconda3/envs/pybpod-env-test/lib/python3.6/site-packages (from pybpod-gui-plugin-stmdiagram==1.0.0) (1.4.2)
Requirement already satisfied: pyparsing>=2.1.4 in /home/henry/anaconda3/envs/pybpod-env-test/lib/python3.6/site-packages (from pydot->pybpod-gui-plugin-stmdiagram==1.0.0) (2.2.0)
Installing collected packages: pybpod-gui-plugin-stmdiagram
  Attempting uninstall: pybpod-gui-plugin-stmdiagram
    Found existing installation: pybpod-gui-plugin-stmdiagram 1.0.0
    Uninstalling pybpod-gui-plugin-stmdiagram-1.0.0:
      Successfully uninstalled pybpod-gui-plugin-stmdiagram-1.0.0
  Running setup.py develop for pybpod-gui-plugin-stmdiagram
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pybpod 1.8.2 requires pybpod-gui-api==1.8.2, but you have pybpod-gui-api 1.8.3b1 which is incompatible.
Successfully installed pybpod-gui-plugin-stmdiagram-1.0.0
Obtaining file:///home/henry/Documents/pybpod-test/plugins/pybpod-gui-plugin-timeline
  Preparing metadata (setup.py) ... done
Installing collected packages: pybpod-gui-plugin-timeline
  Attempting uninstall: pybpod-gui-plugin-timeline
    Found existing installation: pybpod-gui-plugin-timeline 1.0.1
    Uninstalling pybpod-gui-plugin-timeline-1.0.1:
      Successfully uninstalled pybpod-gui-plugin-timeline-1.0.1
  Running setup.py develop for pybpod-gui-plugin-timeline
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pybpod 1.8.2 requires pybpod-gui-api==1.8.2, but you have pybpod-gui-api 1.8.3b1 which is incompatible.
Successfully installed pybpod-gui-plugin-timeline-1.0.1
Obtaining file:///home/henry/Documents/pybpod-test/plugins/pybpod-gui-plugin-trial-timeline
  Preparing metadata (setup.py) ... done
Installing collected packages: pybpod-gui-plugin-trial-timeline
  Attempting uninstall: pybpod-gui-plugin-trial-timeline
    Found existing installation: pybpod-gui-plugin-trial-timeline 1.0.0
    Uninstalling pybpod-gui-plugin-trial-timeline-1.0.0:
      Successfully uninstalled pybpod-gui-plugin-trial-timeline-1.0.0
  Running setup.py develop for pybpod-gui-plugin-trial-timeline
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pybpod 1.8.2 requires pybpod-gui-api==1.8.2, but you have pybpod-gui-api 1.8.3b1 which is incompatible.
Successfully installed pybpod-gui-plugin-trial-timeline-1.0.0
Obtaining file:///home/henry/Documents/pybpod-test/plugins/pybpod-gui-plugin-waveplayer
  Preparing metadata (setup.py) ... done
Installing collected packages: pybpod-gui-plugin-waveplayer
  Attempting uninstall: pybpod-gui-plugin-waveplayer
    Found existing installation: pybpod-gui-plugin-waveplayer 1.0
    Uninstalling pybpod-gui-plugin-waveplayer-1.0:
      Successfully uninstalled pybpod-gui-plugin-waveplayer-1.0
  Running setup.py develop for pybpod-gui-plugin-waveplayer
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pybpod 1.8.2 requires pybpod-gui-api==1.8.2, but you have pybpod-gui-api 1.8.3b1 which is incompatible.
Successfully installed pybpod-gui-plugin-waveplayer-1.0
Obtaining file:///home/henry/Documents/pybpod-test/plugins/pybpod-gui-plugin-rotaryencoder
  Preparing metadata (setup.py) ... done
Installing collected packages: pybpod-gui-plugin-rotaryencoder
  Attempting uninstall: pybpod-gui-plugin-rotaryencoder
    Found existing installation: pybpod-gui-plugin-rotaryencoder 0.1.4
    Uninstalling pybpod-gui-plugin-rotaryencoder-0.1.4:
      Successfully uninstalled pybpod-gui-plugin-rotaryencoder-0.1.4
  Running setup.py develop for pybpod-gui-plugin-rotaryencoder
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pybpod 1.8.2 requires pybpod-gui-api==1.8.2, but you have pybpod-gui-api 1.8.3b1 which is incompatible.
Successfully installed pybpod-gui-plugin-rotaryencoder-0.1.4
```
```bash
Installing collected packages: pybpod-gui-plugin-soundcard
  Attempting uninstall: pybpod-gui-plugin-soundcard
    Found existing installation: pybpod-gui-plugin-soundcard 0.1.6
    Uninstalling pybpod-gui-plugin-soundcard-0.1.6:
      Successfully uninstalled pybpod-gui-plugin-soundcard-0.1.6
  Running setup.py develop for pybpod-gui-plugin-soundcard
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pybpod 1.8.2 requires pybpod-gui-api==1.8.2, but you have pybpod-gui-api 1.8.3b1 which is incompatible.
Successfully installed pybpod-gui-plugin-soundcard-0.1.6
```

the error related to the gui api seems the most relevant

**Comment by HenryJFlynn** [comment]
> ![image](https://user-images.githubusercontent.com/130571023/250827094-dc4df6f8-f64e-41ba-8255-6c7c84598099.png) vs ![image](https://user-images.githubusercontent.com/130571023/250814304-ee5cdde0-4da8-430d-a49e-b8dc7acdcf42.png)
> 
> The working env has less files. How?

The missing files have to do with the three differences pointed out here https://github.com/HenryJFlynn/mouse2afc/issues/25#issuecomment-1619769642

**Comment by HenryJFlynn** [comment]
'/home/henry/Documents/pybpod-environment-test/lib/python3.6/site-packages: pybpodgui_api` this folder contains `board_com.py` which is a file which we modied here https://github.com/HenryJFlynn/pybpod-gui-api/issues/1 to enable the specification of machine type in user settings.

**Comment by HenryJFlynn** [comment]
The problem right now is that running the `python utils/install.py` step does not seem to install the `HenryJFlynn` `pybpod-gui-api` package (with the bf4e0edb52e207d9709f43f9ab0eb8b850107e35 in it). To verify this is actually the case, we are gonna add a dummy variable in a file of that submodule, run `python utils/install.py` and in a ipython session import that dummy variable. If the dummy variable does not exist, then that step command is in fact not installing our package.

**Comment by HenryJFlynn** [comment]
> The problem right now is that running the `python utils/install.py` step does not seem to install the `HenryJFlynn` `pybpod-gui-api` package (with the bf4e0edb52e207d9709f43f9ab0eb8b850107e35 in it). To verify this is actually the case, we are gonna add a dummy variable in a file of that submodule, run `python utils/install.py` and in a ipython session import that dummy variable. If the dummy variable does not exist, then that step command is in fact not installing our package.

Exact problem was doing `cd base/pybpod; pip install -e .` which was overwriting our `pybpod-gui-api` package with an older version (`1.8.2`) which didn't have our changes.

**Comment by HenryJFlynn** [comment]
fixed by 2c4b4cc915c0dcfb15ec64adf210d7286c2124b6.

**Comment by HenryJFlynn** [comment]
Gonna add a projects folder to the mouse2afc repo so that the user does not have to create one(0db62d7) and revise the guide accordingly (74d9a0b).

**Comment by HenryJFlynn** [comment]
found more mistakes

**Comment by HenryJFlynn** [comment]
gonna make mouse2afc a package so that we do not need a step in the user guide to change `MOUSE2AFC_PATH`. See __

**Comment by HenryJFlynn** [comment]
I believe there is no more improvements to be made for now
