### ISSUE TITLE
Fix Bias Calculation

### ISSUE THREAD

**Issue by HenryJFlynn** [HenryJFlynn/mouse2afc#27]

**Comment by HenryJFlynn** [comment]
Trying to run the protocol on the bpod set up with pybpod I get this error:
```
['stderr', '2023-06-16 15:56:58.581357', '', 'Traceback (most recent call last):\n', '', '']
['stderr', '2023-06-16 15:56:58.581392', '', '  File "/home/henry/Documents/pybpod-project/tasks/emulator_mouse2afc_example/emulator_mouse2afc_example.py", line 8, in <module>\n', '', '']
['stderr', '2023-06-16 15:56:58.581509', '', '    ', '', '']
['stderr', '2023-06-16 15:56:58.581539', '', 'Mouse2AFC(bpod).run()', '', '']
['stderr', '2023-06-16 15:56:58.581564', '', '\n', '', '']
['stderr', '2023-06-16 15:56:58.581588', '', '  File "/home/henry/Documents/mouse2afc/mouse2afc.py", line 47, in run\n', '', '']
['stderr', '2023-06-16 15:56:58.581675', '', '    ', '', '']
['stderr', '2023-06-16 15:56:58.581703', '', 'self._data.Custom.update(i_trial)', '', '']
['stderr', '2023-06-16 15:56:58.581727', '', '\n', '', '']
['stderr', '2023-06-16 15:56:58.581751', '', '  File "/home/henry/Documents/mouse2afc/data.py", line 541, in update\n', '', '']
['stderr', '2023-06-16 15:56:58.581945', '', '    ', '', '']
['stderr', '2023-06-16 15:56:58.581974', '', 'PerfL = 1 - (sum(ndxRightRewd) / (LAST_TRIALS * 2))', '', '']
['stderr', '2023-06-16 15:56:58.581999', '', '\n', '', '']
['stderr', '2023-06-16 15:56:58.582026', '', 'TypeError', '', '']
['stderr', '2023-06-16 15:56:58.582049', '', ': ', '', '']
['stderr', '2023-06-16 15:56:58.582071', '', "unsupported operand type(s) for +: 'int' and 'NoneType'", '', '']
['stderr', '2023-06-16 15:56:58.582095', '', '\n', '', '']
```
see
https://github.com/HenryJFlynn/mouse2afc/issues/10#issuecomment-1594637110

**Comment by HenryJFlynn** [comment]
vscode does not have this problem. it works as expected, sum() counts the number of `True`'s in `ndxRightRewd` and is divided by `LAST_TRIALS * 2`. 

I have run it for 10s of trials and it works just fine

**Comment by HenryJFlynn** [comment]
I think this error only pops if there is no choice made which then fills the list with a none value since either left or right was chosen. It is possible that vscode never hit this issue because the virtual mouse always makes a choice

**Comment by HenryJFlynn** [comment]
matlab uses this:
```
choiceBiasTrialsIdxs = find(~isnan(allBiasTrials)) + startTrialBiasCalc - 1;
```
it creates `choiceBiasTrialsIdxs` and uses that variables to index `Trials.LeftRewarded`. Here is it in full:
```matlab
startTrialBiasCalc = iff(iTrial > LAST_TRIALS, iTrial - LAST_TRIALS, 1);
%ndxRewd = BpodSystem.Data.Custom.Trials(indicesRwd:iTrial).Rewarded;
allBiasTrials = [BpodSystem.Data.Custom.Trials(startTrialBiasCalc:iTrial).ChoiceLeft];
choiceBiasTrialsIdxs = find(~isnan(allBiasTrials)) + startTrialBiasCalc - 1;
leftRewarded = sum([...
         BpodSystem.Data.Custom.Trials(choiceBiasTrialsIdxs).LeftRewarded] == 1);
rightRewarded = sum([...
         BpodSystem.Data.Custom.Trials(choiceBiasTrialsIdxs).LeftRewarded] == 0);
leftChoiceBiasTrials = choiceBiasTrialsIdxs([BpodSystem.Data.Custom.Trials(...
                                         choiceBiasTrialsIdxs).ChoiceLeft] == 1);
rightChoiceBiasTrials = setdiff(choiceBiasTrialsIdxs, leftChoiceBiasTrials);
```

**Comment by HenryJFlynn** [comment]
I can achieve something similar in python with:
```python
allBiasTrials = [True, None, True, False]
choiceBiasTrialsIdxs = [i for i, x in enumerate(allBiasTrials) if x isnot None]
```

**Comment by HenryJFlynn** [comment]
Before this line `PerfL = 1 - (sum(ndxRightRewd) / (LAST_TRIALS * 2))` or in it, i could modify `ndxRightRewd` so that any None value is removed. 

I should check matlab first

**Comment by HenryJFlynn** [comment]
I may be best to rewrite this section to update it with the newest matlab version.

**Comment by HenryJFlynn** [comment]
> Before this line `PerfL = 1 - (sum(ndxRightRewd) / (LAST_TRIALS * 2))` or in it, i could modify `ndxRightRewd` so that any None value is removed.
> 
> I should check matlab first

I can create a list with the indices of true and another with false then use the length of that list in the calculation of `PerfL` and `PerfR`

**Comment by HenryJFlynn** [comment]
^^ Found something better https://stackoverflow.com/questions/12229902/sum-a-list-which-contains-none-using-python

**Comment by HenryJFlynn** [comment]
That can fix it but i believe there are some conceptual/logical errors which were created from me messing with the length of i_trial

**Comment by HenryJFlynn** [comment]
The question of is it doing what I want it to do is what takes me a long time to figure out

**Comment by HenryJFlynn** [comment]
^^ restarted and it was fine

**Comment by HenryJFlynn** [comment]
Found another error, changing the value of timeOut_Missed_Choice doesn't seem to do anything nor any other timer. ChoiceDeadline does work tho.
